GET http://localhost:5205/games


###
GET http://localhost:5205/games/4


###
POST http://localhost:5205/games/
Content-Type: application/json

{
    "name": "Call of Duty",
    "genre": "Army Fitting",
    "price": 20.2,
    "releaseDate": "2019-3-8"
}